services:
  - type: web
    name: wschecher
    runtime: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
